# Generated by Django 3.2 on 2021-05-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('adhar_no', models.CharField(default='Noaddharnumber', max_length=100, primary_key=True, serialize=False)),
                ('dob', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('age', models.CharField(default='', max_length=100)),
                ('sex', models.CharField(default='', max_length=100)),
                ('address', models.TextField()),
                ('district', models.CharField(default='Delhi', max_length=100)),
                ('pin', models.IntegerField()),
                ('mob', models.CharField(max_length=100)),
                ('blood_grp', models.CharField(default='', max_length=100)),
                ('weight', models.IntegerField(default='')),
                ('diabetic', models.CharField(default='', max_length=100)),
                ('disease', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
