# Generated by Django 3.2 on 2021-05-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_donator_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
